# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seba/UNIVERSIDAD/TrabajoFinal/tellapic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seba/UNIVERSIDAD/TrabajoFinal/tellapic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seba/UNIVERSIDAD/TrabajoFinal/tellapic/CMakeFiles /home/seba/UNIVERSIDAD/TrabajoFinal/tellapic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seba/UNIVERSIDAD/TrabajoFinal/tellapic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named tellapic

# Build rule for target.
tellapic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tellapic
.PHONY : tellapic

# fast build rule for target.
tellapic/fast:
	$(MAKE) -f CMakeFiles/tellapic.dir/build.make CMakeFiles/tellapic.dir/build
.PHONY : tellapic/fast

#=============================================================================
# Target rules for targets named pytellapic

# Build rule for target.
pytellapic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pytellapic
.PHONY : pytellapic

# fast build rule for target.
pytellapic/fast:
	$(MAKE) -f swig/CMakeFiles/pytellapic.dir/build.make swig/CMakeFiles/pytellapic.dir/build
.PHONY : pytellapic/fast

src/common/common.o: src/common/common.c.o
.PHONY : src/common/common.o

# target to build an object file
src/common/common.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/common.c.o
.PHONY : src/common/common.c.o

src/common/common.i: src/common/common.c.i
.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/common.c.i
.PHONY : src/common/common.c.i

src/common/common.s: src/common/common.c.s
.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/common.c.s
.PHONY : src/common/common.c.s

src/common/console.o: src/common/console.c.o
.PHONY : src/common/console.o

# target to build an object file
src/common/console.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/console.c.o
.PHONY : src/common/console.c.o

src/common/console.i: src/common/console.c.i
.PHONY : src/common/console.i

# target to preprocess a source file
src/common/console.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/console.c.i
.PHONY : src/common/console.c.i

src/common/console.s: src/common/console.c.s
.PHONY : src/common/console.s

# target to generate assembly for a file
src/common/console.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/console.c.s
.PHONY : src/common/console.c.s

src/common/list.o: src/common/list.c.o
.PHONY : src/common/list.o

# target to build an object file
src/common/list.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/list.c.o
.PHONY : src/common/list.c.o

src/common/list.i: src/common/list.c.i
.PHONY : src/common/list.i

# target to preprocess a source file
src/common/list.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/list.c.i
.PHONY : src/common/list.c.i

src/common/list.s: src/common/list.c.s
.PHONY : src/common/list.s

# target to generate assembly for a file
src/common/list.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/list.c.s
.PHONY : src/common/list.c.s

src/lib/tellapic.o: src/lib/tellapic.c.o
.PHONY : src/lib/tellapic.o

# target to build an object file
src/lib/tellapic.c.o:
	$(MAKE) -f CMakeFiles/tellapic.dir/build.make CMakeFiles/tellapic.dir/src/lib/tellapic.c.o
.PHONY : src/lib/tellapic.c.o

src/lib/tellapic.i: src/lib/tellapic.c.i
.PHONY : src/lib/tellapic.i

# target to preprocess a source file
src/lib/tellapic.c.i:
	$(MAKE) -f CMakeFiles/tellapic.dir/build.make CMakeFiles/tellapic.dir/src/lib/tellapic.c.i
.PHONY : src/lib/tellapic.c.i

src/lib/tellapic.s: src/lib/tellapic.c.s
.PHONY : src/lib/tellapic.s

# target to generate assembly for a file
src/lib/tellapic.c.s:
	$(MAKE) -f CMakeFiles/tellapic.dir/build.make CMakeFiles/tellapic.dir/src/lib/tellapic.c.s
.PHONY : src/lib/tellapic.c.s

src/server/server.o: src/server/server.c.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.o
.PHONY : src/server/server.c.o

src/server/server.i: src/server/server.c.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.i
.PHONY : src/server/server.c.i

src/server/server.s: src/server/server.c.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.s
.PHONY : src/server/server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... tellapic"
	@echo "... pytellapic"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/common/console.o"
	@echo "... src/common/console.i"
	@echo "... src/common/console.s"
	@echo "... src/common/list.o"
	@echo "... src/common/list.i"
	@echo "... src/common/list.s"
	@echo "... src/lib/tellapic.o"
	@echo "... src/lib/tellapic.i"
	@echo "... src/lib/tellapic.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

