/**
 *   Copyright (c) 2010 Sebastián Treu.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; version 2 of the License.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 * @author
 *         Sebastian Treu 
 *         sebastian.treu(at)gmail.com
 *
 */  
package ar.com.tellapic;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

import ar.com.tellapic.utils.Utils;

/**
 * @author 
 *          Sebastian Treu
 *          sebastian.treu(at)gmail.com
 *
 */
public class MainDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public static final int CREATE_TAB    = 0;
	public static final int FAVOURITE_TAB = 1;	
	public static final int JOIN_TAB      = 2;

	private boolean userInput;
	private boolean fileSet;
	private boolean hostSet;
	private boolean portSet;
	private boolean userSet;

	private String host;
	private String name;
	private String password;
	private int port;
		
	/** Creates new form NewJFrame */
	public MainDialog() {
		
		initComponents();
		setIconImage(Utils.createIconImage(112, 75, "/icons/logo_small.png"));
		setLocationRelativeTo(null);

		userInput = false;
		hostSet = false;
		fileSet = false;
		portSet = false;
		userSet = false;
	}
	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		createImageArea = new javax.swing.JLabel();
		createCreateButton = new javax.swing.JButton();
		createExitButton = new javax.swing.JButton();
		createFileField = new javax.swing.JTextField();
		createFileLabel = new javax.swing.JLabel();
		createPasswordLabel = new javax.swing.JLabel();
		createPasswordField = new javax.swing.JPasswordField();
		createUsernameField = new javax.swing.JTextField();
		createUsernameLabel = new javax.swing.JLabel();
		createPortLabel = new javax.swing.JLabel();
		createPortField = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		favouriteTable = new javax.swing.JTable();
		favouriteJoinButton = new javax.swing.JButton();
		favouriteExitButton = new javax.swing.JButton();
		favouriteDeleteButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		joinPasswordField = new javax.swing.JPasswordField();
		joinPasswordLabel = new javax.swing.JLabel();
		joinUsernameLabel = new javax.swing.JLabel();
		joinUsernameField = new javax.swing.JTextField();
		joinPortField = new javax.swing.JTextField();
		joinPortLabel = new javax.swing.JLabel();
		joinHostLabel = new javax.swing.JLabel();
		joinHostField = new javax.swing.JTextField();
		joinExitButton = new javax.swing.JButton();
		joinJoinButton = new javax.swing.JButton();
		joinAddFavouriteButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(Utils.msg.getString("MainDialog.0")); //$NON-NLS-1$
		setLocationByPlatform(true);
		setModal(true);
		setResizable(false);
		setUndecorated(true);

		jTabbedPane1.setBackground(java.awt.SystemColor.inactiveCaption);
		jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
		jTabbedPane1.setFocusable(false);
		jTabbedPane1.setMinimumSize(new java.awt.Dimension(221, 390));

		jPanel1.setMaximumSize(new java.awt.Dimension(221, 390));
		jPanel1.setMinimumSize(new java.awt.Dimension(221, 390));

		createImageArea.setToolTipText(Utils.msg.getString("MainDialog.1")); //$NON-NLS-1$
		createImageArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		createImageArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		createImageArea.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				createImageAreaMouseClicked(evt);
			}
		});

		createCreateButton.setText(Utils.msg.getString("MainDialog.2")); //$NON-NLS-1$
		createCreateButton.setEnabled(false);
		
		createExitButton.setText(Utils.msg.getString("MainDialog.3")); //$NON-NLS-1$
		createExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exit(evt);
			}
		});

		createFileField.setEditable(false);
		createFileField.setHorizontalAlignment(SwingConstants.LEFT);
		createFileField.setToolTipText(Utils.msg.getString("MainDialog.4")); //$NON-NLS-1$
		createFileField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		createFileField.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				createFileFieldMouseClicked(evt);
			}
		});

		createFileLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createFileLabel.setText(Utils.msg.getString("MainDialog.5")); //$NON-NLS-1$

		createPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createPasswordLabel.setText(Utils.msg.getString("MainDialog.6")); //$NON-NLS-1$

		createPasswordField.setToolTipText(Utils.msg.getString("MainDialog.7")); //$NON-NLS-1$

		createUsernameField.setToolTipText(Utils.msg.getString("MainDialog.8")); //$NON-NLS-1$
		createUsernameField.setInputVerifier(new NonEmptyVerifier());
		createUsernameField.setName(Utils.msg.getString("MainDialog.9")); // NOI18N //$NON-NLS-1$

		createUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createUsernameLabel.setText(Utils.msg.getString("MainDialog.10")); //$NON-NLS-1$

		createPortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createPortLabel.setText(Utils.msg.getString("MainDialog.11")); //$NON-NLS-1$

		createPortField.setToolTipText(Utils.msg.getString("MainDialog.12")); //$NON-NLS-1$
		createPortField.setInputVerifier(new PortVerifier());
		createPortField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createPortFieldActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(createImageArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(createPortLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createFileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(createPasswordField)
														.addComponent(createPortField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
														.addComponent(createUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
														.addComponent(createFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(createExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(createPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(createPortLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(createUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(createUsernameLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(createPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(createPasswordLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(createFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(createFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(createImageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(createExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addContainerGap())
		);

		jTabbedPane1.addTab(Utils.msg.getString("MainDialog.13"), jPanel1); //$NON-NLS-1$

		jPanel3.setMinimumSize(new java.awt.Dimension(221, 390));
		
		
		favouriteTable.setModel(new FavouritesTableModel());
			
		favouriteTable.setColumnSelectionAllowed(true);
		favouriteTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		favouriteTable.getTableHeader().setReorderingAllowed(false);
		favouriteTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		favouriteTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
			@Override
			public void valueChanged(ListSelectionEvent e) {
				favouriteJoinButton.setEnabled(true);
			}
		});
		
		jScrollPane1.setViewportView(favouriteTable);
		favouriteJoinButton.setText(Utils.msg.getString("MainDialog.18")); //$NON-NLS-1$
		favouriteJoinButton.setEnabled(false);
		favouriteJoinButton.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				FavouritesTableModel model = (FavouritesTableModel) favouriteTable.getModel();
				host = (String) model.getValueAt(favouriteTable.getSelectedRow(), 0);
				port = Integer.parseInt((String) model.getValueAt(favouriteTable.getSelectedRow(), 1));
				name = (String) model.getValueAt(favouriteTable.getSelectedRow(), 2);
				password = (String) model.getValueAt(favouriteTable.getSelectedRow(), 3);
				userInput = true;
				MainDialog.this.dispose();
			}
		});
		
		
		favouriteExitButton.setText(Utils.msg.getString("MainDialog.19")); //$NON-NLS-1$
		favouriteExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				favouriteExitButtonActionPerformed(evt);
			}
		});

		favouriteDeleteButton.setText(Utils.msg.getString("MainDialog.20")); //$NON-NLS-1$
		favouriteDeleteButton.setEnabled(false);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
										.addComponent(favouriteExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
										.addComponent(favouriteDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(favouriteJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
										.addContainerGap())
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(favouriteJoinButton)
								.addComponent(favouriteExitButton)
								.addComponent(favouriteDeleteButton))
								.addContainerGap())
		);

		jTabbedPane1.addTab(Utils.msg.getString("MainDialog.21"), jPanel3); //$NON-NLS-1$

		jPanel2.setMinimumSize(new java.awt.Dimension(221, 390));

		joinPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinPasswordLabel.setText(Utils.msg.getString("MainDialog.22")); //$NON-NLS-1$

		joinUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinUsernameLabel.setText(Utils.msg.getString("MainDialog.23")); //$NON-NLS-1$

		joinUsernameField.setInputVerifier(new NonEmptyVerifier());
		joinUsernameField.setName(Utils.msg.getString("MainDialog.24")); // NOI18N //$NON-NLS-1$

		joinPortField.setInputVerifier(new PortVerifier());

		joinPortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinPortLabel.setText(Utils.msg.getString("MainDialog.25")); //$NON-NLS-1$

		joinHostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinHostLabel.setText(Utils.msg.getString("MainDialog.26")); //$NON-NLS-1$

		joinHostField.setInputVerifier(new NonEmptyVerifier());
		joinHostField.setName(Utils.msg.getString("MainDialog.27")); // NOI18N //$NON-NLS-1$

		joinExitButton.setText(Utils.msg.getString("MainDialog.28")); //$NON-NLS-1$
		joinExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinExitButtonexit(evt);
			}
		});

		joinJoinButton.setText(Utils.msg.getString("MainDialog.29")); //$NON-NLS-1$
		joinJoinButton.setEnabled(false);
		joinJoinButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinJoinButtonActionPerformed(evt);
			}
		});

		joinAddFavouriteButton.setText(Utils.msg.getString("MainDialog.30")); //$NON-NLS-1$
		joinAddFavouriteButton.setEnabled(false);
		joinAddFavouriteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinAddFavouriteButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(joinUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinPortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinHostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
												.addGap(22, 22, 22)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(joinAddFavouriteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinHostField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinUsernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinPortField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
																.addComponent(joinExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(joinJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(16, 16, 16)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(joinHostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(joinHostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(joinPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(joinPortLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(joinUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(joinUsernameLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(joinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(joinPasswordLabel))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(joinAddFavouriteButton)
														.addGap(257, 257, 257)
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(joinExitButton)
																.addComponent(joinJoinButton)))
		);

		jTabbedPane1.addTab(Utils.msg.getString("MainDialog.31"), jPanel2); //$NON-NLS-1$
		jTabbedPane1.addChangeListener(new ChangeListener(){
			@Override
			public void stateChanged(ChangeEvent e) {
				int currentTabIndex = ((JTabbedPane)e.getSource()).getSelectedIndex();

				switch(currentTabIndex) {
				
				case CREATE_TAB:
					createPortField.requestFocus(true);
					break;
					
				case JOIN_TAB:
					joinHostField.requestFocus(true);
					break;
				}
			}
		});
		
		
		getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

		pack();
	}

	
	/*
	 * 
	 */
	private void createPortFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	
	/*
	 * 
	 */
	private void createFileFieldMouseClicked(java.awt.event.MouseEvent evt) {
		createImageAreaMouseClicked(evt);
	}

	
	/**
	 * 
	 * @param evt
	 */
	private void exit(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	
	/*
	 * 
	 */
	private void joinExitButtonexit(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	
	/*
	 * 
	 */
	private void joinJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {
		host = joinHostField.getText();
		name = joinUsernameField.getText();
		password = String.valueOf(joinPasswordField.getPassword());
		port = Integer.parseInt(joinPortField.getText());
		userInput = true;
		MainDialog.this.dispose();
	}

	
	/*
	 * 
	 */
	private void favouriteExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	
	/*
	 * 
	 */
	private void createImageAreaMouseClicked(java.awt.event.MouseEvent evt) {
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(Utils.msg.getString("MainDialog.32"), Utils.msg.getString("MainDialog.33"), Utils.msg.getString("MainDialog.34")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println(Utils.msg.getString("MainDialog.35")+chooser.getSelectedFile().getName()); //$NON-NLS-1$
			createFileField.setText(chooser.getSelectedFile().getAbsolutePath());
			fileSet = true;
			ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath());
			Image     img  = icon.getImage().getScaledInstance(createImageArea.getWidth(), createImageArea.getHeight(), Image.SCALE_SMOOTH);
			icon.setImage(img);
			createImageArea.setIcon(icon);
		} else if ( returnVal == JFileChooser.CANCEL_OPTION) {
			fileSet = false;
		}
		enableButton(jTabbedPane1.getSelectedIndex());
	}

	
	/*
	 * 
	 */
	private void joinAddFavouriteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		FavouritesTableModel model = (FavouritesTableModel) favouriteTable.getModel();
		model.addFavourite(
				joinHostField.getText(),
				Integer.parseInt(joinPortField.getText()),
				joinUsernameField.getText(),
				String.valueOf(joinPasswordField.getPassword())
		);
		
	}



	/* generated */
	private javax.swing.JButton createCreateButton;
	private javax.swing.JButton createExitButton;
	private javax.swing.JTextField createFileField;
	private javax.swing.JLabel createFileLabel;
	private javax.swing.JLabel createImageArea;
	private javax.swing.JPasswordField createPasswordField;
	private javax.swing.JLabel createPasswordLabel;
	private javax.swing.JTextField createPortField;
	private javax.swing.JLabel createPortLabel;
	private javax.swing.JTextField createUsernameField;
	private javax.swing.JLabel createUsernameLabel;
	private javax.swing.JButton favouriteDeleteButton;
	private javax.swing.JButton favouriteExitButton;
	private javax.swing.JButton favouriteJoinButton;
	private javax.swing.JTable favouriteTable;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JButton joinAddFavouriteButton;
	private javax.swing.JButton joinExitButton;
	private javax.swing.JTextField joinHostField;
	private javax.swing.JLabel joinHostLabel;
	private javax.swing.JButton joinJoinButton;
	private javax.swing.JPasswordField joinPasswordField;
	private javax.swing.JLabel joinPasswordLabel;
	private javax.swing.JTextField joinPortField;
	private javax.swing.JLabel joinPortLabel;
	private javax.swing.JTextField joinUsernameField;
	private javax.swing.JLabel joinUsernameLabel;


	/*
	 * 
	 */
	class PortVerifier extends javax.swing.InputVerifier {
		@Override
		public boolean verify(javax.swing.JComponent input) {
			javax.swing.JTextField tf = (javax.swing.JTextField) input;
			int port = 0;
			if (isNumeric(tf.getText())) {
				port = Integer.parseInt(tf.getText());
				if (port <= 1024) {
					tf.setBackground(Color.orange); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
					portSet = false;
				}
				else {
					tf.setBackground(Color.white); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
					portSet = true;
				}
			}
			else {
				tf.setBackground(Color.orange); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
				portSet = false;
			}
			enableButton(jTabbedPane1.getSelectedIndex());  //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
			return portSet;
		}
	}

	
	/*
	 * 
	 */
	private void enableButton(int tabSelected) {
		switch (tabSelected) {
		case CREATE_TAB:
			createCreateButton.setEnabled((portSet && userSet && fileSet));
			break;

		case FAVOURITE_TAB:

			break;

		case JOIN_TAB:
			boolean value = (hostSet && portSet && userSet);
			joinAddFavouriteButton.setEnabled(value);
			joinJoinButton.setEnabled(value);
		}
	}

	/*
	 * 
	 */
	class NonEmptyVerifier extends javax.swing.InputVerifier {
		@Override
		public boolean verify(javax.swing.JComponent input) {
			javax.swing.JTextField tf = (javax.swing.JTextField) input;
			boolean ret = false;
			if (tf.getText().length() == 0) {
				tf.setBackground(Color.orange); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
				if (tf.getName().equals(Utils.msg.getString("MainDialog.36")) || tf.getName().equals(Utils.msg.getString("MainDialog.37"))) //$NON-NLS-1$ //$NON-NLS-2$
					userSet = false;
				else
					hostSet = false;
			} else {
				tf.setBackground(Color.white); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
				ret = true;
				if (tf.getName().equals(Utils.msg.getString("MainDialog.38")) || tf.getName().equals(Utils.msg.getString("MainDialog.39"))) //$NON-NLS-1$ //$NON-NLS-2$
					userSet = true;
				else
					hostSet = true;
			}
			enableButton(jTabbedPane1.getSelectedIndex()); //TODO: this shouldn't be done here. implemente shouldYieldFocus() instead
			return ret;
		}
	}

	
	/*
	 * 
	 */
	private static boolean isNumeric(String aStringValue) {
		Pattern pattern = Pattern.compile("\\d+");
		Matcher matcher = pattern.matcher(aStringValue);
		return matcher.matches();
	}

	
	/**
	 * @return
	 */
	public boolean isUserInput() {
		return userInput;
	}

	/**
	 * @return
	 */
	public String getRemoteHost() {
		return host;
	}

	/**
	 * @return
	 */
	public int getRemotePort() {
		return port;
	}

	/**
	 * @return
	 */
	public String getUsername() {
		return name;
	}

	/**
	 * @return
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @return
	 */
	public int getOption() {
		return jTabbedPane1.getSelectedIndex();
	}
}