# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customChatWidgetUi.ui'
#
# Created: Tue Jul 26 04:28:38 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_chatWidget(object):
    def setupUi(self, chatWidget):
        chatWidget.setObjectName(_fromUtf8("chatWidget"))
        chatWidget.resize(469, 322)
        chatWidget.setWindowTitle(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(chatWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(chatWidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textArea = QtGui.QTextEdit(self.tab)
        self.textArea.setEnabled(True)
        self.textArea.setUndoRedoEnabled(False)
        self.textArea.setReadOnly(True)
        self.textArea.setObjectName(_fromUtf8("textArea"))
        self.verticalLayout_2.addWidget(self.textArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.textField = QtGui.QLineEdit(self.tab)
        self.textField.setObjectName(_fromUtf8("textField"))
        self.horizontalLayout.addWidget(self.textField)
        self.smileyButton = QtGui.QToolButton(self.tab)
        self.smileyButton.setMaximumSize(QtCore.QSize(100, 24))
        self.smileyButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.smileyButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smileyButton.setIcon(icon)
        self.smileyButton.setCheckable(False)
        self.smileyButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.smileyButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.smileyButton.setArrowType(QtCore.Qt.NoArrow)
        self.smileyButton.setObjectName(_fromUtf8("smileyButton"))
        self.horizontalLayout.addWidget(self.smileyButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.actionHeartBreakSmiley = QtGui.QAction(chatWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/heart-break.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHeartBreakSmiley.setIcon(icon1)
        self.actionHeartBreakSmiley.setObjectName(_fromUtf8("actionHeartBreakSmiley"))
        self.actionHeartSmiley = QtGui.QAction(chatWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/heart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHeartSmiley.setIcon(icon2)
        self.actionHeartSmiley.setObjectName(_fromUtf8("actionHeartSmiley"))
        self.actionConfuseSmiley = QtGui.QAction(chatWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-confuse.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfuseSmiley.setIcon(icon3)
        self.actionConfuseSmiley.setObjectName(_fromUtf8("actionConfuseSmiley"))
        self.actionCoolSmiley = QtGui.QAction(chatWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-cool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCoolSmiley.setIcon(icon4)
        self.actionCoolSmiley.setObjectName(_fromUtf8("actionCoolSmiley"))
        self.actionCrySmiley = QtGui.QAction(chatWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-cry.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrySmiley.setIcon(icon5)
        self.actionCrySmiley.setObjectName(_fromUtf8("actionCrySmiley"))
        self.actionDrawSmiley = QtGui.QAction(chatWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-draw.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawSmiley.setIcon(icon6)
        self.actionDrawSmiley.setObjectName(_fromUtf8("actionDrawSmiley"))
        self.actionEekBlueSmiley = QtGui.QAction(chatWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-eek-blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEekBlueSmiley.setIcon(icon7)
        self.actionEekBlueSmiley.setObjectName(_fromUtf8("actionEekBlueSmiley"))
        self.actionEvilSmiley = QtGui.QAction(chatWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-evil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEvilSmiley.setIcon(icon8)
        self.actionEvilSmiley.setObjectName(_fromUtf8("actionEvilSmiley"))
        self.actionGrinSmiley = QtGui.QAction(chatWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-grin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrinSmiley.setIcon(icon9)
        self.actionGrinSmiley.setObjectName(_fromUtf8("actionGrinSmiley"))
        self.actionMadSmiley = QtGui.QAction(chatWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-mad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMadSmiley.setIcon(icon10)
        self.actionMadSmiley.setObjectName(_fromUtf8("actionMadSmiley"))
        self.actionMoneySmiley = QtGui.QAction(chatWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-money.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMoneySmiley.setIcon(icon11)
        self.actionMoneySmiley.setObjectName(_fromUtf8("actionMoneySmiley"))
        self.actionGreenSmiley = QtGui.QAction(chatWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-mr-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGreenSmiley.setIcon(icon12)
        self.actionGreenSmiley.setObjectName(_fromUtf8("actionGreenSmiley"))
        self.actionTongueSmiley = QtGui.QAction(chatWidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-razz.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTongueSmiley.setIcon(icon13)
        self.actionTongueSmiley.setObjectName(_fromUtf8("actionTongueSmiley"))
        self.actionRedSmiley = QtGui.QAction(chatWidget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedSmiley.setIcon(icon14)
        self.actionRedSmiley.setObjectName(_fromUtf8("actionRedSmiley"))
        self.actionWinkSmiley = QtGui.QAction(chatWidget)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/smiley-wink.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWinkSmiley.setIcon(icon15)
        self.actionWinkSmiley.setObjectName(_fromUtf8("actionWinkSmiley"))
        self.actionYesSmiley = QtGui.QAction(chatWidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/thumb-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionYesSmiley.setIcon(icon16)
        self.actionYesSmiley.setObjectName(_fromUtf8("actionYesSmiley"))
        self.actionNoSmiley = QtGui.QAction(chatWidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/smileys/thumb.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNoSmiley.setIcon(icon17)
        self.actionNoSmiley.setObjectName(_fromUtf8("actionNoSmiley"))

        self.retranslateUi(chatWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.textField, QtCore.SIGNAL(_fromUtf8("returnPressed()")), chatWidget.updateLastText)
        QtCore.QMetaObject.connectSlotsByName(chatWidget)

    def retranslateUi(self, chatWidget):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("chatWidget", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeartBreakSmiley.setText(QtGui.QApplication.translate("chatWidget", "heartBreakSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeartBreakSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "</3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeartSmiley.setText(QtGui.QApplication.translate("chatWidget", "heartSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeartSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "<3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfuseSmiley.setText(QtGui.QApplication.translate("chatWidget", "confuseSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfuseSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ":S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoolSmiley.setText(QtGui.QApplication.translate("chatWidget", "coolSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoolSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "8)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCrySmiley.setText(QtGui.QApplication.translate("chatWidget", "crySmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCrySmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ";(", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawSmiley.setText(QtGui.QApplication.translate("chatWidget", "drawSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ":u", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEekBlueSmiley.setText(QtGui.QApplication.translate("chatWidget", "eekBlueSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEekBlueSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "o.o", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvilSmiley.setText(QtGui.QApplication.translate("chatWidget", "evilSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvilSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "(6)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrinSmiley.setText(QtGui.QApplication.translate("chatWidget", "grinSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrinSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ":D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMadSmiley.setText(QtGui.QApplication.translate("chatWidget", "madSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMadSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ">(", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoneySmiley.setText(QtGui.QApplication.translate("chatWidget", "moneySmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoneySmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "$$", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGreenSmiley.setText(QtGui.QApplication.translate("chatWidget", "greenSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGreenSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ">D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTongueSmiley.setText(QtGui.QApplication.translate("chatWidget", "tongueSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTongueSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ":P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedSmiley.setText(QtGui.QApplication.translate("chatWidget", "redSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ":$", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWinkSmiley.setText(QtGui.QApplication.translate("chatWidget", "winkSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWinkSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", ";)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYesSmiley.setText(QtGui.QApplication.translate("chatWidget", "yesSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionYesSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "(y)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoSmiley.setText(QtGui.QApplication.translate("chatWidget", "noSmiley", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoSmiley.setToolTip(QtGui.QApplication.translate("chatWidget", "(n)", None, QtGui.QApplication.UnicodeUTF8))

import rsrc_rc
