# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolBox.ui'
#
# Created: Fri Jul 29 19:54:17 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName(_fromUtf8("ToolBox"))
        ToolBox.resize(285, 689)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/logo_small.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.setWindowIcon(icon)
        ToolBox.setAutoFillBackground(True)
        ToolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.drawingPage = QtGui.QWidget()
        self.drawingPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.drawingPage.setObjectName(_fromUtf8("drawingPage"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.drawingPage)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.scrollArea_6 = QtGui.QScrollArea(self.drawingPage)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName(_fromUtf8("scrollArea_6"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 263, 422))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.tableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents_6)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_15.addWidget(self.tableWidget)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_14.addWidget(self.scrollArea_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/property.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.drawingPage, icon1, _fromUtf8(""))
        self.strokeStylePage = QtGui.QWidget()
        self.strokeStylePage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.strokeStylePage.setObjectName(_fromUtf8("strokeStylePage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.strokeStylePage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.strokeStylePage)
        self.scrollArea.setMinimumSize(QtCore.QSize(235, 0))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet(_fromUtf8("QScrollArea::title { \n"
"    background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:2 13px;\n"
" } \n"
"\n"
"QScrollArea { \n"
"     border: 2px solid gray;\n"
"     background-color: lightgray;\n"
"     border-radius: 5px; \n"
" } "))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 261, 420))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 181))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.widthSpinner = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.widthSpinner.setMinimumSize(QtCore.QSize(0, 0))
        self.widthSpinner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widthSpinner.setAccelerated(True)
        self.widthSpinner.setObjectName(_fromUtf8("widthSpinner"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.widthSpinner)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.squareCapButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.squareCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.squareCapButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capsquare.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.squareCapButton.setIcon(icon2)
        self.squareCapButton.setIconSize(QtCore.QSize(18, 18))
        self.squareCapButton.setCheckable(True)
        self.squareCapButton.setObjectName(_fromUtf8("squareCapButton"))
        self.endCapsButtonGroup = QtGui.QButtonGroup(ToolBox)
        self.endCapsButtonGroup.setObjectName(_fromUtf8("endCapsButtonGroup"))
        self.endCapsButtonGroup.addButton(self.squareCapButton)
        self.horizontalLayout.addWidget(self.squareCapButton)
        self.roundCapButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.roundCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.roundCapButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capround.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roundCapButton.setIcon(icon3)
        self.roundCapButton.setIconSize(QtCore.QSize(18, 18))
        self.roundCapButton.setCheckable(True)
        self.roundCapButton.setDefault(False)
        self.roundCapButton.setFlat(False)
        self.roundCapButton.setObjectName(_fromUtf8("roundCapButton"))
        self.endCapsButtonGroup.addButton(self.roundCapButton)
        self.horizontalLayout.addWidget(self.roundCapButton)
        self.flatCapButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.flatCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.flatCapButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capbutt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flatCapButton.setIcon(icon4)
        self.flatCapButton.setIconSize(QtCore.QSize(18, 18))
        self.flatCapButton.setCheckable(True)
        self.flatCapButton.setObjectName(_fromUtf8("flatCapButton"))
        self.endCapsButtonGroup.addButton(self.flatCapButton)
        self.horizontalLayout.addWidget(self.flatCapButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.roundJoinButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.roundJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.roundJoinButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinround.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roundJoinButton.setIcon(icon5)
        self.roundJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.roundJoinButton.setCheckable(True)
        self.roundJoinButton.setObjectName(_fromUtf8("roundJoinButton"))
        self.lineJoinsButtonGroup = QtGui.QButtonGroup(ToolBox)
        self.lineJoinsButtonGroup.setObjectName(_fromUtf8("lineJoinsButtonGroup"))
        self.lineJoinsButtonGroup.addButton(self.roundJoinButton)
        self.horizontalLayout_2.addWidget(self.roundJoinButton)
        self.miterJoinButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.miterJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.miterJoinButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinmiter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.miterJoinButton.setIcon(icon6)
        self.miterJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.miterJoinButton.setCheckable(True)
        self.miterJoinButton.setObjectName(_fromUtf8("miterJoinButton"))
        self.lineJoinsButtonGroup.addButton(self.miterJoinButton)
        self.horizontalLayout_2.addWidget(self.miterJoinButton)
        self.bevelJoinButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.bevelJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.bevelJoinButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinbevel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bevelJoinButton.setIcon(icon7)
        self.bevelJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.bevelJoinButton.setCheckable(True)
        self.bevelJoinButton.setObjectName(_fromUtf8("bevelJoinButton"))
        self.lineJoinsButtonGroup.addButton(self.bevelJoinButton)
        self.horizontalLayout_2.addWidget(self.bevelJoinButton)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dashCombo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.dashCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.dashCombo.setObjectName(_fromUtf8("dashCombo"))
        self.horizontalLayout_3.addWidget(self.dashCombo)
        self.dashPhaseSpinner = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.dashPhaseSpinner.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dashPhaseSpinner.setAccelerated(True)
        self.dashPhaseSpinner.setDecimals(1)
        self.dashPhaseSpinner.setObjectName(_fromUtf8("dashPhaseSpinner"))
        self.horizontalLayout_3.addWidget(self.dashPhaseSpinner)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/tool-icons/drawings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.strokeStylePage, icon8, _fromUtf8(""))
        self.strokeColorPage = QtGui.QWidget()
        self.strokeColorPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.strokeColorPage.setObjectName(_fromUtf8("strokeColorPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.strokeColorPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea_2 = QtGui.QScrollArea(self.strokeColorPage)
        self.scrollArea_2.setStyleSheet(_fromUtf8("QScrollArea::title { \n"
"    background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:2 13px;\n"
" } \n"
"\n"
"QScrollArea { \n"
"     border: 2px solid gray;\n"
"     background-color: lightgray;\n"
"     border-radius: 5px; \n"
" } "))
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 261, 420))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.strokeColor = ColorWidget(self.scrollAreaWidgetContents_2)
        self.strokeColor.setObjectName(_fromUtf8("strokeColor"))
        self.verticalLayout_4.addWidget(self.strokeColor)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setContentsMargins(9, 0, 9, 9)
        self.formLayout_2.setHorizontalSpacing(22)
        self.formLayout_2.setVerticalSpacing(9)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.strokeColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.strokeColorLabel.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid \n"
"}"))
        self.strokeColorLabel.setText(_fromUtf8(""))
        self.strokeColorLabel.setObjectName(_fromUtf8("strokeColorLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.strokeColorLabel)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.shouldStrokeCheckbox = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.shouldStrokeCheckbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.shouldStrokeCheckbox.setText(_fromUtf8(""))
        self.shouldStrokeCheckbox.setObjectName(_fromUtf8("shouldStrokeCheckbox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.shouldStrokeCheckbox)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/tool-icons/color1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.strokeColorPage, icon9, _fromUtf8(""))
        self.strokeFillPage = QtGui.QWidget()
        self.strokeFillPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.strokeFillPage.setAutoFillBackground(True)
        self.strokeFillPage.setObjectName(_fromUtf8("strokeFillPage"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.strokeFillPage)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea_3 = QtGui.QScrollArea(self.strokeFillPage)
        self.scrollArea_3.setAutoFillBackground(True)
        self.scrollArea_3.setStyleSheet(_fromUtf8("QScrollArea::title { \n"
"    background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:2 13px;\n"
" } \n"
"\n"
"QScrollArea { \n"
"     border: 2px solid gray;\n"
"     background-color: lightgray;\n"
"     border-radius: 5px; \n"
" } \n"
""))
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 261, 420))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_3.setAutoFillBackground(True)
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.fillColor = ColorWidget(self.scrollAreaWidgetContents_3)
        self.fillColor.setObjectName(_fromUtf8("fillColor"))
        self.verticalLayout_5.addWidget(self.fillColor)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_3.setContentsMargins(9, 0, 9, 9)
        self.formLayout_3.setHorizontalSpacing(22)
        self.formLayout_3.setVerticalSpacing(9)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.fillColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.fillColorLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fillColorLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fillColorLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fillColorLabel.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid black;\n"
"}"))
        self.fillColorLabel.setText(_fromUtf8(""))
        self.fillColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fillColorLabel.setObjectName(_fromUtf8("fillColorLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.fillColorLabel)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.shouldFillCheckbox = QtGui.QCheckBox(self.scrollAreaWidgetContents_3)
        self.shouldFillCheckbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.shouldFillCheckbox.setAutoFillBackground(False)
        self.shouldFillCheckbox.setText(_fromUtf8(""))
        self.shouldFillCheckbox.setObjectName(_fromUtf8("shouldFillCheckbox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.shouldFillCheckbox)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.addWidget(self.scrollArea_3)
        ToolBox.addItem(self.strokeFillPage, icon9, _fromUtf8(""))
        self.fontPage = QtGui.QWidget()
        self.fontPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.fontPage.setObjectName(_fromUtf8("fontPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fontPage)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea_4 = QtGui.QScrollArea(self.fontPage)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_4.setStyleSheet(_fromUtf8("QScrollArea::title { \n"
"    background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:2 13px;\n"
" } \n"
"\n"
"QScrollArea { \n"
"     border: 2px solid gray;\n"
"     background-color: lightgray;\n"
"     border-radius: 5px; \n"
" } \n"
""))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 261, 420))
        self.scrollAreaWidgetContents_4.setMinimumSize(QtCore.QSize(180, 0))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.fontComboBox = QtGui.QFontComboBox(self.scrollAreaWidgetContents_4)
        self.fontComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.fontComboBox)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fontStyleBoldButton = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.fontStyleBoldButton.setMaximumSize(QtCore.QSize(24, 24))
        self.fontStyleBoldButton.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fontStyleBoldButton.setIcon(icon10)
        self.fontStyleBoldButton.setIconSize(QtCore.QSize(18, 18))
        self.fontStyleBoldButton.setCheckable(True)
        self.fontStyleBoldButton.setObjectName(_fromUtf8("fontStyleBoldButton"))
        self.horizontalLayout_6.addWidget(self.fontStyleBoldButton)
        self.fontStyleItalicButton = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.fontStyleItalicButton.setMaximumSize(QtCore.QSize(24, 24))
        self.fontStyleItalicButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/italic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fontStyleItalicButton.setIcon(icon11)
        self.fontStyleItalicButton.setIconSize(QtCore.QSize(18, 18))
        self.fontStyleItalicButton.setCheckable(True)
        self.fontStyleItalicButton.setObjectName(_fromUtf8("fontStyleItalicButton"))
        self.horizontalLayout_6.addWidget(self.fontStyleItalicButton)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.fontSizeSpinner = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.fontSizeSpinner.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fontSizeSpinner.setAccelerated(True)
        self.fontSizeSpinner.setObjectName(_fromUtf8("fontSizeSpinner"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.fontSizeSpinner)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.fontTextArea = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_4)
        self.fontTextArea.setMinimumSize(QtCore.QSize(0, 0))
        self.fontTextArea.setObjectName(_fromUtf8("fontTextArea"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.fontTextArea)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.charCounter = QtGui.QLCDNumber(self.scrollAreaWidgetContents_4)
        self.charCounter.setFrameShape(QtGui.QFrame.NoFrame)
        self.charCounter.setNumDigits(3)
        self.charCounter.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.charCounter.setProperty(_fromUtf8("value"), 512.0)
        self.charCounter.setObjectName(_fromUtf8("charCounter"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.charCounter)
        self.verticalLayout_8.addLayout(self.formLayout_4)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.scrollArea_4)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/tool-icons/text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.fontPage, icon12, _fromUtf8(""))
        self.usersPage = QtGui.QWidget()
        self.usersPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.usersPage.setObjectName(_fromUtf8("usersPage"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.usersPage)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scrollArea_5 = QtGui.QScrollArea(self.usersPage)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 263, 422))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.treeWidget = QtGui.QTreeWidget(self.scrollAreaWidgetContents_5)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(False)
        self.verticalLayout_11.addWidget(self.treeWidget)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_10.addWidget(self.scrollArea_5)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/users.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.usersPage, icon13, _fromUtf8(""))
        self.chatPage = QtGui.QWidget()
        self.chatPage.setGeometry(QtCore.QRect(0, 0, 283, 442))
        self.chatPage.setObjectName(_fromUtf8("chatPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.chatPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.chatWidget = CustomChatWidget(self.chatPage)
        self.chatWidget.setObjectName(_fromUtf8("chatWidget"))
        self.verticalLayout_7.addWidget(self.chatWidget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/chat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.chatPage, icon14, _fromUtf8(""))
        self.actionCapSquare = QtGui.QAction(ToolBox)
        self.actionCapSquare.setCheckable(True)
        self.actionCapSquare.setIcon(icon2)
        self.actionCapSquare.setObjectName(_fromUtf8("actionCapSquare"))
        self.actionCapRound = QtGui.QAction(ToolBox)
        self.actionCapRound.setCheckable(True)
        self.actionCapRound.setIcon(icon3)
        self.actionCapRound.setObjectName(_fromUtf8("actionCapRound"))
        self.actionCapFlat = QtGui.QAction(ToolBox)
        self.actionCapFlat.setCheckable(True)
        self.actionCapFlat.setIcon(icon4)
        self.actionCapFlat.setObjectName(_fromUtf8("actionCapFlat"))
        self.actionJoinRound = QtGui.QAction(ToolBox)
        self.actionJoinRound.setCheckable(True)
        self.actionJoinRound.setIcon(icon5)
        self.actionJoinRound.setObjectName(_fromUtf8("actionJoinRound"))
        self.actionJoinMiter = QtGui.QAction(ToolBox)
        self.actionJoinMiter.setCheckable(True)
        self.actionJoinMiter.setIcon(icon6)
        self.actionJoinMiter.setObjectName(_fromUtf8("actionJoinMiter"))
        self.actionJoinBevel = QtGui.QAction(ToolBox)
        self.actionJoinBevel.setCheckable(True)
        self.actionJoinBevel.setIcon(icon7)
        self.actionJoinBevel.setObjectName(_fromUtf8("actionJoinBevel"))
        self.actionStrokeColor = QtGui.QAction(ToolBox)
        self.actionStrokeColor.setIcon(icon9)
        self.actionStrokeColor.setObjectName(_fromUtf8("actionStrokeColor"))
        self.actionFillColor = QtGui.QAction(ToolBox)
        self.actionFillColor.setIcon(icon9)
        self.actionFillColor.setObjectName(_fromUtf8("actionFillColor"))
        self.actionShouldFill = QtGui.QAction(ToolBox)
        self.actionShouldFill.setCheckable(True)
        self.actionShouldFill.setObjectName(_fromUtf8("actionShouldFill"))
        self.actionShouldStroke = QtGui.QAction(ToolBox)
        self.actionShouldStroke.setCheckable(True)
        self.actionShouldStroke.setObjectName(_fromUtf8("actionShouldStroke"))
        self.actionWidthChange = QtGui.QAction(ToolBox)
        self.actionWidthChange.setObjectName(_fromUtf8("actionWidthChange"))
        self.actionDashSet = QtGui.QAction(ToolBox)
        self.actionDashSet.setObjectName(_fromUtf8("actionDashSet"))
        self.actionDashPhaseChange = QtGui.QAction(ToolBox)
        self.actionDashPhaseChange.setObjectName(_fromUtf8("actionDashPhaseChange"))
        self.actionFontStyleBold = QtGui.QAction(ToolBox)
        self.actionFontStyleBold.setCheckable(True)
        self.actionFontStyleBold.setIcon(icon10)
        self.actionFontStyleBold.setObjectName(_fromUtf8("actionFontStyleBold"))
        self.actionFontStyleItalic = QtGui.QAction(ToolBox)
        self.actionFontStyleItalic.setCheckable(True)
        self.actionFontStyleItalic.setIcon(icon11)
        self.actionFontStyleItalic.setObjectName(_fromUtf8("actionFontStyleItalic"))
        self.actionFontFamilySet = QtGui.QAction(ToolBox)
        self.actionFontFamilySet.setIcon(icon12)
        self.actionFontFamilySet.setObjectName(_fromUtf8("actionFontFamilySet"))
        self.actionFontSizeSet = QtGui.QAction(ToolBox)
        self.actionFontSizeSet.setObjectName(_fromUtf8("actionFontSizeSet"))
        self.actionChangeCharCounter = QtGui.QAction(ToolBox)
        self.actionChangeCharCounter.setObjectName(_fromUtf8("actionChangeCharCounter"))

        self.retranslateUi(ToolBox)
        ToolBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.shouldFillCheckbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionShouldFill.toggle)
        QtCore.QObject.connect(self.roundCapButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCapRound.toggle)
        QtCore.QObject.connect(self.dashCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.actionDashSet.trigger)
        QtCore.QObject.connect(self.widthSpinner, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.actionWidthChange.trigger)
        QtCore.QObject.connect(self.bevelJoinButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionJoinBevel.toggle)
        QtCore.QObject.connect(self.miterJoinButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionJoinMiter.toggle)
        QtCore.QObject.connect(self.flatCapButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCapFlat.toggle)
        QtCore.QObject.connect(self.squareCapButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionCapSquare.toggle)
        QtCore.QObject.connect(self.roundJoinButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionJoinRound.toggle)
        QtCore.QObject.connect(self.dashPhaseSpinner, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.actionDashPhaseChange.trigger)
        QtCore.QObject.connect(self.fontTextArea, QtCore.SIGNAL(_fromUtf8("textChanged()")), self.actionChangeCharCounter.trigger)
        QtCore.QObject.connect(self.fontComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.actionFontFamilySet.trigger)
        QtCore.QObject.connect(self.fontSizeSpinner, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.actionFontSizeSet.trigger)
        QtCore.QObject.connect(self.fontStyleBoldButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionFontStyleBold.toggle)
        QtCore.QObject.connect(self.fontStyleItalicButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionFontStyleItalic.toggle)
        QtCore.QObject.connect(self.strokeColor, QtCore.SIGNAL(_fromUtf8("colorChanged(QColor)")), ToolBox.strokeColorChanged)
        QtCore.QObject.connect(self.fillColor, QtCore.SIGNAL(_fromUtf8("colorChanged(QColor)")), ToolBox.fillColorChanged)
        QtCore.QObject.connect(self.shouldStrokeCheckbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionShouldStroke.toggle)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        ToolBox.setWindowTitle(QtGui.QApplication.translate("ToolBox", "ToolBox", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setStyleSheet(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ToolBox", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ToolBox", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("ToolBox", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ToolBox", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ToolBox", "Value", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.drawingPage), QtGui.QApplication.translate("ToolBox", "Drawing Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ToolBox", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ToolBox", "Caps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ToolBox", "Joins:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ToolBox", "Dash:", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.strokeStylePage), QtGui.QApplication.translate("ToolBox", "Stroke Style", None, QtGui.QApplication.UnicodeUTF8))
        self.strokeColor.setToolTip(QtGui.QApplication.translate("ToolBox", "Custom color widget", None, QtGui.QApplication.UnicodeUTF8))
        self.strokeColor.setWhatsThis(QtGui.QApplication.translate("ToolBox", "You don\'t care", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ToolBox", "Current Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ToolBox", "Stroke Enabled:", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.strokeColorPage), QtGui.QApplication.translate("ToolBox", "Stroke Color", None, QtGui.QApplication.UnicodeUTF8))
        self.fillColor.setToolTip(QtGui.QApplication.translate("ToolBox", "Custom color widget", None, QtGui.QApplication.UnicodeUTF8))
        self.fillColor.setWhatsThis(QtGui.QApplication.translate("ToolBox", "You don\'t care", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ToolBox", "Current Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ToolBox", "Fill Enabled:", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.strokeFillPage), QtGui.QApplication.translate("ToolBox", "Fill Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ToolBox", "Family:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ToolBox", "Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ToolBox", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ToolBox", "Text:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ToolBox", "Char left:", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.fontPage), QtGui.QApplication.translate("ToolBox", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("ToolBox", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("ToolBox", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("ToolBox", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("ToolBox", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("ToolBox", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("ToolBox", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("ToolBox", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("ToolBox", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("ToolBox", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(4).setText(0, QtGui.QApplication.translate("ToolBox", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        ToolBox.setItemText(ToolBox.indexOf(self.usersPage), QtGui.QApplication.translate("ToolBox", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.chatWidget.setToolTip(QtGui.QApplication.translate("ToolBox", "Custom widget", None, QtGui.QApplication.UnicodeUTF8))
        self.chatWidget.setWhatsThis(QtGui.QApplication.translate("ToolBox", "You don\'t care", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.chatPage), QtGui.QApplication.translate("ToolBox", "Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCapSquare.setText(QtGui.QApplication.translate("ToolBox", "capSquare", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCapRound.setText(QtGui.QApplication.translate("ToolBox", "capRound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCapFlat.setText(QtGui.QApplication.translate("ToolBox", "capFlat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJoinRound.setText(QtGui.QApplication.translate("ToolBox", "joinRound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJoinMiter.setText(QtGui.QApplication.translate("ToolBox", "joinMiter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJoinBevel.setText(QtGui.QApplication.translate("ToolBox", "joinBevel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStrokeColor.setText(QtGui.QApplication.translate("ToolBox", "strokeColor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFillColor.setText(QtGui.QApplication.translate("ToolBox", "fillColor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShouldFill.setText(QtGui.QApplication.translate("ToolBox", "shouldFill", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShouldStroke.setText(QtGui.QApplication.translate("ToolBox", "shouldStroke", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWidthChange.setText(QtGui.QApplication.translate("ToolBox", "widthChange", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDashSet.setText(QtGui.QApplication.translate("ToolBox", "dashSet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDashPhaseChange.setText(QtGui.QApplication.translate("ToolBox", "dashPhaseChange", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontStyleBold.setText(QtGui.QApplication.translate("ToolBox", "fontStyleBold", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontStyleItalic.setText(QtGui.QApplication.translate("ToolBox", "fontStyleItalic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontFamilySet.setText(QtGui.QApplication.translate("ToolBox", "fontFamilySet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontSizeSet.setText(QtGui.QApplication.translate("ToolBox", "fontSizeSet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChangeCharCounter.setText(QtGui.QApplication.translate("ToolBox", "changeCharCounter", None, QtGui.QApplication.UnicodeUTF8))

from ColorWidget import ColorWidget
from CustomChatWidget import CustomChatWidget
import rsrc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ToolBox = QtGui.QToolBox()
    ui = Ui_ToolBox()
    ui.setupUi(ToolBox)
    ToolBox.show()
    sys.exit(app.exec_())

