/**
 *   Copyright (c) 2010 Sebastián Treu.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; version 2 of the License.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 * @author
 *         Sebastian Treu 
 *         sebastian.treu(at)gmail.com
 *
 */  
package ar.com.tellapic;

import java.awt.Color;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author 
 *          Sebastian Treu
 *          sebastian.treu(at)gmail.com
 *
 */
public class MainDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public static final int CREATE_TAB = 0;
	public static final int FAVOURITE_TAB = 1;	
	public static final int JOIN_TAB = 2;

	private boolean userInput;
	private boolean fileSet;
	private boolean hostSet;
	private boolean portSet;
	private boolean userSet;

	/** Creates new form NewJFrame */
	public MainDialog() {

		initComponents();

		this.setLocationRelativeTo(null);

		userInput = false;
		hostSet = false;
		fileSet = false;
		portSet = false;
		userSet = false;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		createImageArea = new javax.swing.JLabel();
		createCreateButton = new javax.swing.JButton();
		createExitButton = new javax.swing.JButton();
		createFileField = new javax.swing.JTextField();
		createFileLabel = new javax.swing.JLabel();
		createPasswordLabel = new javax.swing.JLabel();
		createPasswordField = new javax.swing.JPasswordField();
		createUsernameField = new javax.swing.JTextField();
		createUsernameLabel = new javax.swing.JLabel();
		createPortLabel = new javax.swing.JLabel();
		createPortField = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		favouriteTable = new javax.swing.JTable();
		favouriteJoinButton = new javax.swing.JButton();
		favouriteExitButton = new javax.swing.JButton();
		favouriteDeleteButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		joinPasswordField = new javax.swing.JPasswordField();
		joinPasswordLabel = new javax.swing.JLabel();
		joinUsernameLabel = new javax.swing.JLabel();
		joinUsernameField = new javax.swing.JTextField();
		joinPortField = new javax.swing.JTextField();
		joinPortLabel = new javax.swing.JLabel();
		joinHostLabel = new javax.swing.JLabel();
		joinHostField = new javax.swing.JTextField();
		joinExitButton = new javax.swing.JButton();
		joinJoinButton = new javax.swing.JButton();
		joinAddFavouriteButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Choose");
		setLocationByPlatform(true);
		setModal(true);
		setResizable(false);
		setUndecorated(true);

		jTabbedPane1.setBackground(java.awt.SystemColor.inactiveCaption);
		jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
		jTabbedPane1.setFocusable(false);
		jTabbedPane1.setMinimumSize(new java.awt.Dimension(221, 390));

		jPanel1.setMaximumSize(new java.awt.Dimension(221, 390));
		jPanel1.setMinimumSize(new java.awt.Dimension(221, 390));

		createImageArea.setToolTipText("Click here to choose the file you wish to share/discuss.");
		createImageArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		createImageArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		createImageArea.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				createImageAreaMouseClicked(evt);
			}
		});

		createCreateButton.setText("Create");
		createCreateButton.setEnabled(false);
		
		createExitButton.setText("Exit");
		createExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exit(evt);
			}
		});

		createFileField.setEditable(false);
		createFileField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		createFileField.setToolTipText("The file you want to share/discuss.");
		createFileField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		createFileField.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				createFileFieldMouseClicked(evt);
			}
		});

		createFileLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createFileLabel.setText("File:");

		createPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createPasswordLabel.setText("Password:");

		createPasswordField.setToolTipText("The password to protect undesirable connections.");

		createUsernameField.setToolTipText("The user name you choose for your session.");
		createUsernameField.setInputVerifier(new NonEmptyVerifier());
		createUsernameField.setName("createUsernameField"); // NOI18N

		createUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createUsernameLabel.setText("Username:");

		createPortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		createPortLabel.setText("Port:");

		createPortField.setToolTipText("Set the listening sertver port. It should be greater than 1024.");
		createPortField.setInputVerifier(new PortVerifier());
		createPortField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createPortFieldActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(createImageArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(createPortLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createFileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
												.addComponent(createUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(createPasswordField)
														.addComponent(createPortField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
														.addComponent(createUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
														.addComponent(createFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(createExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(createPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(createPortLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(createUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(createUsernameLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(createPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(createPasswordLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(createFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(createFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(createImageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(createExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addContainerGap())
		);

		jTabbedPane1.addTab("Start session", jPanel1);

		jPanel3.setMinimumSize(new java.awt.Dimension(221, 390));

		favouriteTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {

				},
				new String [] {
						"Host", "Port", "User", "Pwd"
				}
		) {
			Class[] types = new Class [] {
					java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
			};

			public Class getColumnClass(int columnIndex) {
				return types [columnIndex];
			}
		});
		favouriteTable.setColumnSelectionAllowed(true);
		favouriteTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		favouriteTable.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(favouriteTable);
		favouriteTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

		favouriteJoinButton.setText("Join");
		favouriteJoinButton.setEnabled(false);

		favouriteExitButton.setText("Exit");
		favouriteExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				favouriteExitButtonActionPerformed(evt);
			}
		});

		favouriteDeleteButton.setText("Delete");
		favouriteDeleteButton.setEnabled(false);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
										.addComponent(favouriteExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
										.addComponent(favouriteDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(favouriteJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
										.addContainerGap())
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(favouriteJoinButton)
								.addComponent(favouriteExitButton)
								.addComponent(favouriteDeleteButton))
								.addContainerGap())
		);

		jTabbedPane1.addTab("Favourites", jPanel3);

		jPanel2.setMinimumSize(new java.awt.Dimension(221, 390));

		joinPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinPasswordLabel.setText("Password:");

		joinUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinUsernameLabel.setText("Username:");

		joinUsernameField.setInputVerifier(new NonEmptyVerifier());
		joinUsernameField.setName("joinUsernameField"); // NOI18N

		joinPortField.setInputVerifier(new PortVerifier());
		joinPortField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinPortFieldActionPerformed(evt);
			}
		});

		joinPortLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinPortLabel.setText("Port:");

		joinHostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		joinHostLabel.setText("Host:");

		joinHostField.setInputVerifier(new NonEmptyVerifier());
		joinHostField.setName("joinHostField"); // NOI18N

		joinExitButton.setText("Exit");
		joinExitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinExitButtonexit(evt);
			}
		});

		joinJoinButton.setText("Join");
		joinJoinButton.setEnabled(false);
		joinJoinButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinJoinButtonActionPerformed(evt);
			}
		});

		joinAddFavouriteButton.setText("Add to Favourite");
		joinAddFavouriteButton.setEnabled(false);
		joinAddFavouriteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinAddFavouriteButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(joinUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinPortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
												.addComponent(joinHostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
												.addGap(22, 22, 22)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(joinAddFavouriteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinHostField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinUsernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
														.addComponent(joinPortField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
																.addComponent(joinExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(joinJoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(16, 16, 16)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(joinHostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(joinHostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(joinPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(joinPortLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(joinUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(joinUsernameLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(joinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(joinPasswordLabel))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(joinAddFavouriteButton)
														.addGap(257, 257, 257)
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(joinExitButton)
																.addComponent(joinJoinButton)))
		);

		jTabbedPane1.addTab("Join Session", jPanel2);

		getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

		pack();
	}

	private void createPortFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void createFileFieldMouseClicked(java.awt.event.MouseEvent evt) {
		createImageAreaMouseClicked(evt);
	}

	private void joinPortFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void exit(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	private void joinExitButtonexit(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	private void joinJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {
		userInput = true;
		MainDialog.this.dispose();
	}

	private void favouriteExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		MainDialog.this.dispose();
	}

	private void createImageAreaMouseClicked(java.awt.event.MouseEvent evt) {
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println("You chose to open this file: "+chooser.getSelectedFile().getName());
			createFileField.setText(chooser.getSelectedFile().getAbsolutePath());
			fileSet = true;
			ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath());
			Image     img  = icon.getImage().getScaledInstance(createImageArea.getWidth(), createImageArea.getHeight(), Image.SCALE_SMOOTH);
			icon.setImage(img);
			createImageArea.setIcon(icon);
		} else if ( returnVal == JFileChooser.CANCEL_OPTION) {
			fileSet = false;
		}
		enableButton(jTabbedPane1.getSelectedIndex());
	}

	private void joinAddFavouriteButtonActionPerformed(java.awt.event.ActionEvent evt) {

	}



	// Variables declaration - do not modify
	private javax.swing.JButton createCreateButton;
	private javax.swing.JButton createExitButton;
	private javax.swing.JTextField createFileField;
	private javax.swing.JLabel createFileLabel;
	private javax.swing.JLabel createImageArea;
	private javax.swing.JPasswordField createPasswordField;
	private javax.swing.JLabel createPasswordLabel;
	private javax.swing.JTextField createPortField;
	private javax.swing.JLabel createPortLabel;
	private javax.swing.JTextField createUsernameField;
	private javax.swing.JLabel createUsernameLabel;
	private javax.swing.JButton favouriteDeleteButton;
	private javax.swing.JButton favouriteExitButton;
	private javax.swing.JButton favouriteJoinButton;
	private javax.swing.JTable favouriteTable;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JButton joinAddFavouriteButton;
	private javax.swing.JButton joinExitButton;
	private javax.swing.JTextField joinHostField;
	private javax.swing.JLabel joinHostLabel;
	private javax.swing.JButton joinJoinButton;
	private javax.swing.JPasswordField joinPasswordField;
	private javax.swing.JLabel joinPasswordLabel;
	private javax.swing.JTextField joinPortField;
	private javax.swing.JLabel joinPortLabel;
	private javax.swing.JTextField joinUsernameField;
	private javax.swing.JLabel joinUsernameLabel;


	class PortVerifier extends javax.swing.InputVerifier {
		public boolean verify(javax.swing.JComponent input) {
			javax.swing.JTextField tf = (javax.swing.JTextField) input;
			int port = 0;
			if (isNumeric(tf.getText())) {
				port = Integer.parseInt(tf.getText());
				if (port <= 1024) {
					tf.setBackground(Color.orange);
					portSet = false;
				}
				else {
					tf.setBackground(Color.white);
					portSet = true;
				}
			}
			else {
				tf.setBackground(Color.orange);
				portSet = false;
			}
			enableButton(jTabbedPane1.getSelectedIndex());
			return portSet;
		}
	}

	private void enableButton(int tabSelected) {
		switch (tabSelected) {
		case CREATE_TAB:
			createCreateButton.setEnabled((portSet && userSet && fileSet));
			break;

		case FAVOURITE_TAB:

			break;

		case JOIN_TAB:
			boolean value = (hostSet && portSet && userSet);
			joinAddFavouriteButton.setEnabled(value);
			joinJoinButton.setEnabled(value);
		}
	}

	class NonEmptyVerifier extends javax.swing.InputVerifier {
		public boolean verify(javax.swing.JComponent input) {
			javax.swing.JTextField tf = (javax.swing.JTextField) input;
			boolean ret = false;
			if (tf.getText().length() == 0) {
				tf.setBackground(Color.orange);
				if (tf.getName().equals("createUsernameField") || tf.getName().equals("joinUsernameField"))
					userSet = false;
				else
					hostSet = false;
			} else {
				tf.setBackground(Color.white);
				ret = true;
				if (tf.getName().equals("createUsernameField") || tf.getName().equals("joinUsernameField"))
					userSet = true;
				else
					hostSet = true;
			}
			enableButton(jTabbedPane1.getSelectedIndex());
			return ret;
		}
	}

	public static boolean isNumeric(String aStringValue) {
		Pattern pattern = Pattern.compile("\\d+");
		Matcher matcher = pattern.matcher(aStringValue);
		return matcher.matches();
	}

	/**
	 * @return
	 */
	public boolean isUserInput() {
		return userInput;
	}

	/**
	 * @return
	 */
	public String getRemoteHost() {
		return joinHostField.getText();
	}

	/**
	 * @return
	 */
	public int getRemotePort() {
		return Integer.parseInt(joinPortField.getText());
	}

	/**
	 * @return
	 */
	public String getJoinUsername() {
		return joinUsernameField.getText();
	}

	/**
	 * @return
	 */
	public String getJoinPassword() {
		return String.copyValueOf(joinPasswordField.getPassword());
	}

	/**
	 * @return
	 */
	public int getOption() {
		return jTabbedPane1.getSelectedIndex();
	}
}