# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strokeStyleWidget.ui'
#
# Created: Sun Oct 16 22:45:12 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_StrokeStyleWidget(object):
    def setupUi(self, StrokeStyleWidget):
        StrokeStyleWidget.setObjectName(_fromUtf8("StrokeStyleWidget"))
        StrokeStyleWidget.resize(400, 300)
        StrokeStyleWidget.setWindowTitle(QtGui.QApplication.translate("StrokeStyleWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(StrokeStyleWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(StrokeStyleWidget)
        self.label_3.setText(QtGui.QApplication.translate("StrokeStyleWidget", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.widthSpinner = QtGui.QDoubleSpinBox(StrokeStyleWidget)
        self.widthSpinner.setMinimumSize(QtCore.QSize(0, 0))
        self.widthSpinner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widthSpinner.setAccelerated(True)
        self.widthSpinner.setObjectName(_fromUtf8("widthSpinner"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.widthSpinner)
        self.label = QtGui.QLabel(StrokeStyleWidget)
        self.label.setText(QtGui.QApplication.translate("StrokeStyleWidget", "Caps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.squareCapButton = QtGui.QPushButton(StrokeStyleWidget)
        self.squareCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.squareCapButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capsquare.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.squareCapButton.setIcon(icon)
        self.squareCapButton.setIconSize(QtCore.QSize(18, 18))
        self.squareCapButton.setCheckable(True)
        self.squareCapButton.setObjectName(_fromUtf8("squareCapButton"))
        self.horizontalLayout.addWidget(self.squareCapButton)
        self.roundCapButton = QtGui.QPushButton(StrokeStyleWidget)
        self.roundCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.roundCapButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capround.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roundCapButton.setIcon(icon1)
        self.roundCapButton.setIconSize(QtCore.QSize(18, 18))
        self.roundCapButton.setCheckable(True)
        self.roundCapButton.setDefault(False)
        self.roundCapButton.setFlat(False)
        self.roundCapButton.setObjectName(_fromUtf8("roundCapButton"))
        self.horizontalLayout.addWidget(self.roundCapButton)
        self.flatCapButton = QtGui.QPushButton(StrokeStyleWidget)
        self.flatCapButton.setMaximumSize(QtCore.QSize(32, 32))
        self.flatCapButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/capbutt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flatCapButton.setIcon(icon2)
        self.flatCapButton.setIconSize(QtCore.QSize(18, 18))
        self.flatCapButton.setCheckable(True)
        self.flatCapButton.setObjectName(_fromUtf8("flatCapButton"))
        self.horizontalLayout.addWidget(self.flatCapButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtGui.QLabel(StrokeStyleWidget)
        self.label_2.setText(QtGui.QApplication.translate("StrokeStyleWidget", "Joins:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.roundJoinButton = QtGui.QPushButton(StrokeStyleWidget)
        self.roundJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.roundJoinButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinround.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roundJoinButton.setIcon(icon3)
        self.roundJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.roundJoinButton.setCheckable(True)
        self.roundJoinButton.setObjectName(_fromUtf8("roundJoinButton"))
        self.horizontalLayout_2.addWidget(self.roundJoinButton)
        self.miterJoinButton = QtGui.QPushButton(StrokeStyleWidget)
        self.miterJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.miterJoinButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinmiter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.miterJoinButton.setIcon(icon4)
        self.miterJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.miterJoinButton.setCheckable(True)
        self.miterJoinButton.setObjectName(_fromUtf8("miterJoinButton"))
        self.horizontalLayout_2.addWidget(self.miterJoinButton)
        self.bevelJoinButton = QtGui.QPushButton(StrokeStyleWidget)
        self.bevelJoinButton.setMaximumSize(QtCore.QSize(32, 32))
        self.bevelJoinButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/app-icons/joinbevel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bevelJoinButton.setIcon(icon5)
        self.bevelJoinButton.setIconSize(QtCore.QSize(18, 18))
        self.bevelJoinButton.setCheckable(True)
        self.bevelJoinButton.setObjectName(_fromUtf8("bevelJoinButton"))
        self.horizontalLayout_2.addWidget(self.bevelJoinButton)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(StrokeStyleWidget)
        self.label_4.setText(QtGui.QApplication.translate("StrokeStyleWidget", "Dash:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dashCombo = QtGui.QComboBox(StrokeStyleWidget)
        self.dashCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.dashCombo.setObjectName(_fromUtf8("dashCombo"))
        self.horizontalLayout_3.addWidget(self.dashCombo)
        self.dashPhaseSpinner = QtGui.QDoubleSpinBox(StrokeStyleWidget)
        self.dashPhaseSpinner.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dashPhaseSpinner.setAccelerated(True)
        self.dashPhaseSpinner.setDecimals(1)
        self.dashPhaseSpinner.setObjectName(_fromUtf8("dashPhaseSpinner"))
        self.horizontalLayout_3.addWidget(self.dashPhaseSpinner)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(StrokeStyleWidget)
        self.label_5.setText(QtGui.QApplication.translate("StrokeStyleWidget", "Miter Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(StrokeStyleWidget)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(StrokeStyleWidget)
        QtCore.QMetaObject.connectSlotsByName(StrokeStyleWidget)

    def retranslateUi(self, StrokeStyleWidget):
        pass

import rsrc_rc
